### ISSUE TITLE
No custom styles for disabled options

### ISSUE THREAD

**Issue by braydentraas** [MaxKeppeler/bottom-sheets#10]
It would be really helpful to be able to style the disabled options, specifically the text color or opacity, icon color or opacity, and possibly remove the "selectableItemBackground" for disabled options.

When using the default android gray button colors (light mode), it's not immediately clear which option (white or gray) is enabled or disabled, because the disabled option looks similar to the default (enabled) android button style. Being able to change the disabled text color would make it more clear. 

![image](https://user-images.githubusercontent.com/67397523/102644298-6fc17480-4115-11eb-8c73-730b01823a83.png)

**Comment by MaxKeppeler** [comment]
I agree with your suggestion. 

I actually thought about giving the image and the text a lower opacity, as I did in the CalendarSheet for days when the past or future timelines, or individual dates, are disabled. On the other hand I'm not sure if a disabled option with lower opacity is distinguishable enough compared to the normal selectable options. How does that sound to you?

In short, providing the following style attributes would help you out:
- Custom style attr for custom disabled text color
- Custom style attr for custom disabled image color
- Custom style attr for custom disabled background color 

In any way, I will disable the ripple animation for a disabled (or disabled & selected) option. This should be the standard behavior in my opinion.

**Comment by MaxKeppeler** [comment]
Why is the buttons view in your OptionsSheet only white? Did you remove the text of the buttons? 
There is a method to hide the buttons view itself.

**Comment by braydentraas** [comment]
@maxkeppeler 

My apologies, I didn't see this until now. Thanks for the update!

I've put this app on hold for now but the changes you made look very promising. Thanks!
