### ISSUE TITLE
Multiple Instances with Fragments

### ISSUE THREAD

**Issue by irvine752** [MaxKeppeler/bottom-sheets#11]
For some reason I'm getting multiple instances of the OptionSheet. For instance, if I open up FragmentX & then open up the OptionSheet, the next time I open up another instance FragmentX & open up the OptionSheet again.  I will have have to deal with 2 instances of the OptionSheet.

**Comment by MaxKeppeler** [comment]
Where do you show the OptionsSheet within your Fragment?

**Comment by irvine752** [comment]
It's getting triggered from a menu selection, and the call happens from onOptionsItemSelected within the fragment. I only have one main activity that replaces fragments in a framelayout container. Each of those fragments can have smaller subcomponents such as tabs & etcs. The particular fragment is a tab through the com.ogaclejapan.smarttablayout.SmartTabLayout library.

**Comment by MaxKeppeler** [comment]
Could you show me your project or a basic sample that has this behavior so that I can debug it? 
I would check it out right after work this evening.

**Comment by irvine752** [comment]
That works for me. Do you have an email so I can send a sample of the code?

**Comment by MaxKeppeler** [comment]
Yes sure - me@maxkeppeler.com

**Comment by MaxKeppeler** [comment]
It was not a bug in the library. ```onOptionsItemSelected``` was called multiple times due to returning ```super.onOptionMenuSelected```.
