### ISSUE TITLE
Bottom sheet for error messages.

### ISSUE THREAD

**Issue by adarshpugalia** [MaxKeppeler/bottom-sheets#14]
**Describe the solution you'd like**
A bottom sheet to display error messages.

**Comment by MaxKeppeler** [comment]
Could you explain, why the InfoSheet is not good enough to display error messages? You can add text there and soon add a custom drawable with custom color. Would that be enough?

**Comment by MaxKeppeler** [comment]
Please let me know, otherwise I will close this issue.
