### ISSUE TITLE
Button Option Enhancements

### ISSUE THREAD

**Issue by irvine752** [MaxKeppeler/bottom-sheets#16]
**Describe the solution you'd like**
Request to add more features for the Buttons:
1) Buttons with border off 
2) Buttons with border on + circular shape + radius + border color + custom background on or off
3) Buttons with border on + rectangular shape + corner radius + border color +  custom background on or off
 
I think you have text color already, so that's covered for the buttons. The custom background can just be a custom color configuration.

**Comment by MaxKeppeler** [comment]
Will now offer various level of controls over the buttons. 
- Set corner family and radius for negative and positive button in general
- Set button style of negative and positive button (outlined button, text button, normal colored button)
- Set corner family and radius of only positive and negative button, plus fine control for each corner of each button
