### ISSUE TITLE
Color Sheet disableSwitchColorView icon remains

### ISSUE THREAD

**Issue by Fennec-exe** [MaxKeppeler/bottom-sheets#23]
**Describe the bug**
On the color sheet, `disableSwitchColorView()` disables the ability to switch to the custom color view. However, the icon still remains - it just doesn't do anything.

**Library Version:**
1.1.0

**To Reproduce**
1. Add `disableSwitchColorView()` to the code
2. The icon to switch the color view remains

**Expected behavior**
The icon should go away if `disableSwitchColorView()` is enabled.

**Screenshots**
I've attached a video showing this bug in the sample app

[Sample app](https://user-images.githubusercontent.com/74878137/103444136-90cdad80-4c5d-11eb-961e-3af6a62ea061.mp4)

**Comment by MaxKeppeler** [comment]
Thank you a lot. I'm sorry for the 2 issues you have reported - I've rushed a bit with the release.
