### ISSUE TITLE
crashes on configuration change

### ISSUE THREAD

**Issue by mohamadjavadx** [MaxKeppeler/bottom-sheets#24]
**Describe the bug**
the sample app crashes on configuration change while showing some bottom-sheets

**Library Version:**
1.1.1

**To Reproduce**
open a multipleChoices bottom-sheet and rotate phone

**Expected behavior**
the app should not crash and also app **should maintain state of bottom-sheet and selected options**

**Additional context**
maybe some navigationComponent-ish changes could help

**Comment by MaxKeppeler** [comment]
Found the issue. However, isn't the normal behavior of bottom sheets to dismiss at configuration change?

**Comment by mohamadjavadx** [comment]
thanks for quick response, also check out fragment new dependency (1.3.0-rc01) it's pretty much stable and provide new ways to do things
