### ISSUE TITLE
Positive and negative buttons get pushed out of the screen using OptionsSheet.

### ISSUE THREAD

**Issue by puntogris** [MaxKeppeler/bottom-sheets#26]
**Describe the bug**
When adding an amount of options in `OptionsSheet` that will cover the screen in `DisplayMode.LIST` ( it's like 11 for me), the positive and negative buttons get pushed out of the screen.

**Library Version:**
1.1.2

**Comment by MaxKeppeler** [comment]
For the available bottom sheets with adapters, using a constrained height for the bottom sheet type layout will fix this. Thanks for reporting.
