### ISSUE TITLE
Rename peekHeight to peakHeight

### ISSUE THREAD

**Issue by mbilalakmal** [MaxKeppeler/bottom-sheets#3]
If I understand correctly setting the peekHeight will set the maximum height of the bottom sheet. The correct term would be `peak` in that case.

**Comment by MaxKeppeler** [comment]
This might be a bit confusing at first glance, but it is correct. The ``` peekHeight```  is the height of the bottom sheet when it is collapsed. They used peek (peep, at first glance, snap a look, ...) to describe the **visually maximum height** of the bottom sheet when it's in the **collapsed** state. From this state, you can pull the bottom sheet up (expanded state) until it fits to the height of the content or until the maximum available height on the screen, which could be described as the peak.

See the method in the ```BottomSheetBehavior``` class by Google: 
https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetBehavior#setpeekheight

Hope that makes it clear!
