### ISSUE TITLE
A typo in some of your functions

### ISSUE THREAD

**Issue by KaustubhPatange** [MaxKeppeler/bottom-sheets#4]
Upon looking at the code I found out you made a typo [here](https://github.com/MaxKeppeler/bottom-sheets/blob/e96c1e2059c26928590756bb058233730f2b1174/core/src/main/java/com/maxkeppeler/bottomsheets/core/BottomSheet.kt#L151) & a similar one [here](https://github.com/MaxKeppeler/bottom-sheets/blob/e96c1e2059c26928590756bb058233730f2b1174/core/src/main/java/com/maxkeppeler/bottomsheets/core/BottomSheet.kt#L156).

```diff
-  fun cloeButtonDrawable(...)
+  fun closeButtonDrawable(...)
```

**Comment by MaxKeppeler** [comment]
Oh, no. Will fix it now. Thanks!
