### ISSUE TITLE
Input check box uses "default" to set default value, which is a reserved keyword in java.

### ISSUE THREAD

**Issue by adarshpugalia** [MaxKeppeler/bottom-sheets#8]
I am trying to use this library with Java, and the input check box uses the default method to set value, which is a default keyword in java, and hence I am not able to set a default value.

**Comment by MaxKeppeler** [comment]
It's a Kotlin library, but I guess it should work well in general in your java project? 
I agree that this has to be changed. I will change the method to ```defaultValue(...)```.

**Comment by adarshpugalia** [comment]
The library works fine in java, I'm just facing an issue because of the reserved keyword! By the way, the project looks great! Kudos!

**Comment by adarshpugalia** [comment]
By the way, I see a commit for the issue, but I do not see a new version. Do you need to roll up the version?

**Comment by MaxKeppeler** [comment]
I will fix the other current issues and then create a new release. At the latest, I will create one this evening (MEZ). Thanks a lot and great that it works otherwise fine in a Java project!
