### ISSUE TITLE
No option to disable icons for options sheet.

### ISSUE THREAD

**Issue by adarshpugalia** [MaxKeppeler/bottom-sheets#9]
Sometimes, there are no icons to be used for list of options, and I just want the use the options sheet to be able to display a list of options.

There should be a way to disable icons, and left align the options. Currently not settings icons, leaves a significant blank space to the left of the options text.

**Comment by MaxKeppeler** [comment]
The OptionsSheet without Icons works fine for the list view, but in the grid view are icons necessary. I'm unsure right now, if I should throw an exception if the options have no icons and are displayed in a grid, or not and let them just look bad in the grid view.
